PAGE_EVENTS = 0

INIT = PAGE_EVENTS + 1
DESTROY = PAGE_EVENTS + 2
MESSAGE = PAGE_EVENTS + 3
CALLBACK = PAGE_EVENTS + 4
COMMAND = PAGE_EVENTS + 5
MEDIA = PAGE_EVENTS + 6

UI_EVENTS = PAGE_EVENTS + 1000

BUTTON_CLICKED = UI_EVENTS + 1
