MAIN_PAGE_REPLY_KEYBOARD_CAPTION_KEY = 'Main menu'
SETTINGS_PAGE_REPLY_KEYBOARD_CAPTION_KEY = 'Settings'
INTERACTION_PAGE_REPLY_KEYBOARD_CAPTION_KEY = 'Interactive Actions'
SAY_PAGE_REPLY_KEYBOARD_CAPTION_KEY = 'Send me a text and I will say it on the target machine'
