MAIN_PAGE_REPLY_KEYBOARD_CAPTION_KEY = 'Main menu'
SETTINGS_PAGE_REPLY_KEYBOARD_CAPTION_KEY = 'Settings'
INTERACTION_PAGE_REPLY_KEYBOARD_CAPTION_KEY = 'Interactive Actions'
SAY_PAGE_REPLY_KEYBOARD_CAPTION_KEY = 'Send me a text and I will say it on the target machine'
MUSIC_PAGE_REPLY_KEYBOARD_CAPTION_KEY = 'Send me music or voice message and I will play it on the target machine'
BEEP_PAGE_REPLY_KEYBOARD_CAPTION_KEY = 'Choose the beep frequency or send custom'
LANGUAGE_PAGE_REPLY_KEYBOARD_CAPTION_KEY = 'Language Settings'
